apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "accurate.fullname" . }}-manager-role
  labels:
    {{- include "accurate.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - accurate.cybozu.com
    resources:
      - subnamespaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - accurate.cybozu.com
    resources:
      - subnamespaces/finalizers
    verbs:
      - update
  - apiGroups:
      - accurate.cybozu.com
    resources:
      - subnamespaces/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "accurate.fullname" . }}-subnamespace-editor-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    {{- include "accurate.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - accurate.cybozu.com
    resources:
      - subnamespaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - accurate.cybozu.com
    resources:
      - subnamespaces/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "accurate.fullname" . }}-subnamespace-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    {{- include "accurate.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - accurate.cybozu.com
    resources:
      - subnamespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - accurate.cybozu.com
    resources:
      - subnamespaces/status
    verbs:
      - get
