apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "accurate.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    # Labels to be propagated to sub-namespaces.
    labelKeys:
    - team

    # Annotations to be propagated to sub-namespaces.
    annotationKeys:
    # An example to propagate an annotation for MetalLB
    # https://metallb.universe.tf/usage/#requesting-specific-ips
    - metallb.universe.tf/address-pool

    # List of GVK for namespace-scoped resources that can be propagated.
    # Any namespace-scoped resource is allowed.
    watches:
    - group: rbac.authorization.k8s.io
      version: v1
      kind: Role
    - group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
    - version: v1
      kind: Secret
