apiVersion: v1
kind: Service
metadata:
  name: {{ template "accurate.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "accurate.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: webhook-server
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: accurate
