apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "accurate.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "accurate.labels" . | nindent 4 }}
