apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ template "accurate.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ template "accurate.fullname" . }}-serving-cert
  labels:
    {{- include "accurate.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ template "accurate.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-v1-namespace
    failurePolicy: Fail
    name: vnamespace.kb.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - namespaces
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ template "accurate.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-accurate-cybozu-com-v1-subnamespace
    failurePolicy: Fail
    name: vsubnamespace.kb.io
    rules:
      - apiGroups:
          - accurate.cybozu.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - subnamespaces
    sideEffects: None
