name: Lint and Test Charts

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  lint-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup helm-docs
        run: |
          HELM_DOCS_VERSION="$(awk '/HELM_DOCS_VERSION/ && NR <= 10 {print $3}' Makefile)"
          OS=$(uname)
          ARCH=$(uname -i)
          curl -L -sS https://github.com/norwoodj/helm-docs/releases/download/v"${HELM_DOCS_VERSION}"/helm-docs_"${HELM_DOCS_VERSION}"_${OS}_${ARCH}.tar.gz \
            | tar zx -C /tmp
          sudo mv /tmp/helm-docs /usr/local/bin

      - name: Run helm-docs
        run: helm-docs && git diff --no-patch --exit-code

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Apply cert-manager
        run: |
          kubectl apply -f https://github.com/jetstack/cert-manager/releases/latest/download/cert-manager.yaml
          kubectl -n cert-manager wait --for=condition=available --timeout=180s --all deployments

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml
